name: 1 - Build and Upload Artifact

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Display Go Version
        run: go version
      
      - name: Install Dependencies
        run: go get .

      - name: Build for Windows
        run: go build -o cobaia.exe 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: programa windows
          path: cobaia.exe

      