name: 2 - Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Display Go Version
        run: go version
      
      - name: Install Dependencies
        run: go get .

      - name: Build for Windows
        run: go build -o cobaia.exe 

      - name: list files
        run: ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cobaia.exe
          path: ./cobaia.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: cobaia.exe
